name: Bunny

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      web:
        image: python:3.10
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Flask app
      run: |
        nohup python app.py &
        sleep 10

    - name: Health check
      run: |
        curl -f http://localhost:5000

    - name: Output Docker logs on failure
      if: failure()
      run: |
        container_id=$(docker ps -q --filter "name=web")
        if [ -n "$container_id" ]; then
          docker logs "$container_id"
        fi

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push'
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        touch .nojekyll
        echo "Build successful, deploying to GitHub Pages"
        git init
        git add .
        git commit -m "Deploy to GitHub Pages"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:gh-pages
